export const products = [
  {
    id: "mobil-delvac-1300-15w40",
    name: "Mobil Delvac 1300 Super 15W-40",
    category: "Lubricantes Diésel",
    brand: "Mobil",
    price: 110.00,
    description: "Aceite premium para motores diésel de servicio pesado, ideal para flotas, maquinaria agrícola y camiones en Colombia.",
    image: "/16_mobil_delvac_1300_super_15w40.png",
    features: ["Protección excepcional contra el desgaste", "Excelente control del hollín", "Extiende la vida del motor"],
    inStock: true,
  },
  {
    id: "shell-rimula-r4-15w40",
    name: "Shell Rimula R4 X 15W-40",
    category: "Lubricantes Diésel",
    brand: "Shell",
    price: 105.50,
    description: "Aceite multigrado de alto rendimiento que protege contra la corrosión y el desgaste bajo cualquier condición de carga.",
    image: "/14_shell_rimula_r4x_15w40.png",
    features: ["Triple acción protectora", "Control de ácidos", "Limpieza del motor"],
    inStock: true,
  },
  {
    id: "castrol-edge-5w30",
    name: "Castrol EDGE 5W-30 Sintético",
    category: "Lubricantes Gasolina",
    brand: "Castrol",
    price: 180.00,
    description: "Aceite de motor avanzado totalmente sintético. Transforma su estructura bajo presión para mantener separados los metales.",
    image: "/castrol.png",
    features: ["Máximo rendimiento del motor", "Reduce la fricción", "Tecnología Fluid TITANIUM"],
    inStock: true,
  },
  {
    id: "liqui-moly-mos2-10w40",
    name: "Liqui Moly MoS2 Leichtlauf 10W-40",
    category: "Lubricantes Gasolina",
    brand: "Liqui Moly",
    price: 160.00,
    description: "Aceite de motor semisintético con disulfuro de molibdeno (MoS2) para una protección extrema contra el desgaste.",
    image: "/liquimoly.png",
    features: ["Marcha suave", "Excelente protección contra desgaste", "Reducción de consumo de aceite"],
    inStock: true,
  },
  {
    id: "terpel-oiltec-20w50",
    name: "Terpel Oiltec 20W-50",
    category: "Lubricantes Gasolina",
    brand: "Terpel",
    price: 65.00,
    description: "Aceite mineral de alta calidad desarrollado especialmente para las condiciones y el parque automotor de Colombia.",
    image: "/12_terpel_oiltec_10w40_titanio.png",
    features: ["Gran estabilidad térmica", "Protección de motores con alto kilometraje"],
    inStock: true,
  },
  {
    id: "motul-motylgear-75w90",
    name: "Motul Motylgear 75W-90",
    category: "Aceite Motor Transmisión",
    brand: "Motul",
    price: 95.00,
    description: "Lubricante Technosynthese® para cajas de velocidades y puentes. Facilita el paso de marchas.",
    image: "/transmision.png",
    features: ["Extrema presión", "Anti-desgaste", "Anti-corrosión y anti-espuma"],
    inStock: true,
  },
  {
    id: "chevron-ursa-hydraulic-68",
    name: "Chevron Hydraulic Oil AW 68",
    category: "Aceites Hidráulicos",
    brand: "Chevron",
    price: 85.00,
    description: "Fluido hidráulico antidesgaste formulado para maquinaria pesada, excavadoras y equipos industriales.",
    image: "/chevron.png",
    features: ["Protección de bombas hidráulicas", "Buena filtrabilidad", "Resistencia a la oxidación"],
    inStock: true,
  },
  {
    id: "total-glacelf-coolant",
    name: "TotalEnergies Glacelf Auto Supra",
    category: "Coolant Motor",
    brand: "TotalEnergies",
    price: 45.00,
    description: "Anticongelante y refrigerante de larga duración a base de monoetilenglicol con aditivos orgánicos.",
    image: "/coolant.png",
    features: ["Protección anticongelante", "Prevención de corrosión", "Tecnología OAT"],
    inStock: true,
  },
  {
    id: "motul-dot-4",
    name: "Motul DOT 4 Brake Fluid",
    category: "Líquido de Frenos",
    brand: "Motul",
    price: 35.00,
    description: "Líquido de frenos sintético 100% poliglicol para sistemas hidráulicos de frenos y embragues.",
    image: "/frenos-liq.png",
    features: ["Alto punto de ebullición", "Seguridad en frenadas extremas", "Neutro con juntas"],
    inStock: true,
  },
  {
    id: "donaldson-filtro-aire",
    name: "Filtro de Aire Donaldson HD",
    category: "Filtros",
    brand: "Donaldson",
    price: 60.00,
    description: "Filtro de alta eficiencia para maquinaria de construcción y agrícola en entornos polvorientos.",
    image: "/filtro-aire.png",
    features: ["Retención de 99.9% polvo", "Mayor duración del motor"],
    inStock: true,
  },
  {
    id: "mobil-grease-xhp-222",
    name: "Mobilgrease XHP 222",
    category: "Grasas y Aditivos",
    brand: "Mobil",
    price: 25.00,
    description: "Grasa de complejo de litio de servicio extendido, con gran adherencia y resistencia al lavado por agua.",
    image: "/caneca.png",
    features: ["Uso automotriz e industrial", "Excelente protección contra óxido", "Soporta altas temperaturas"],
    inStock: true,
  }
];


export function getProductById(id) {
  return products.find(p => p.id === id);
}
