import { frenosSuspensionProducts } from "../data/frenosSuspensionProducts.js";
import { brandPanelProducts } from "../data/brandPanelProducts.js";
import { catalogoProveedoresProducts } from "../data/catalogoProveedoresProducts.js";

function brakeApplication({
  id, name, slug, brand, reference, image, vehicleBrands, models,
  years = "", axle = "Eje delantero", engine = "", fmsi, oe, source = "", fitments = [],
  fitmentStatus = "verified",
}) {
  const verifiedFitments = fitments.length > 0 ? fitments : [{
    make: vehicleBrands,
    model: models,
    engine,
    years,
    position: axle,
  }];
  return {
    id,
    name,
    slug,
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: brand, slug: brand.toLowerCase().replace(/[^a-z0-9]+/g, "-") },
    price: 0,
    sku: reference,
    referenceType: "manufacturer",
    fitmentStatus,
    fitments: verifiedFitments,
    fitmentSummary: `${reference}: ${models}; ${years}; ${axle.toLowerCase()}.${engine ? ` Motor ${engine}.` : ""}`,
    fitmentRequirements: ["VIN", "año", "motor", "versión", "eje", "sistema de freno"],
    fitmentSource: source,
    shortDesc: `${axle} para ${models}.`,
    description: `${name}. Aplicación de catálogo para ${vehicleBrands}: ${models} (${years}), ${axle.toLowerCase()}${engine ? `, motor ${engine}` : ""}. Confirmar VIN y versión antes del despacho.`,
    image,
    images: [{ url: image, alt: name, isMain: true }],
    imageStatus: "illustrative-family",
    attributes: [
      { id: `${id}-ref`, name: "Referencia", value: reference },
      { id: `${id}-axis`, name: "Posición", value: axle },
      { id: `${id}-status`, name: "Estado de compatibilidad", value: fitmentStatus === "verified" ? "Aplicación verificada por referencia fabricante" : "Compatibilidad condicionada; validar catálogo vigente y VIN" },
      { id: `${id}-models`, name: fitmentStatus === "verified" ? "Aplicaciones verificadas" : "Aplicaciones por validar", value: `${vehicleBrands} ${models} (${years})${engine ? ` · ${engine}` : ""} · ${axle}` },
      ...(fmsi ? [{ id: `${id}-fmsi`, name: "FMSI", value: fmsi }] : []),
      ...(oe ? [{ id: `${id}-oe`, name: "OE", value: oe }] : []),
      ...(source ? [{ id: `${id}-source`, name: "Fuente técnica", value: source }] : []),
      { id: `${id}-image`, name: "Imagen", value: "Imagen de familia; confirmar que el empaque recibido muestre la referencia indicada" },
    ],
    inStock: false,
    stock: 0,
  };
}

const allProducts = [
  // LUBRICANTES GASOLINA
  {
    id: "castrol-edge-5w30",
    name: "Castrol EDGE 5W-30 Sintético",
    slug: "castrol-edge-5w30",
    category: { name: "Lubricantes Gasolina", slug: "lubricantes-gasolina" },
    brand: { name: "Castrol", slug: "castrol" },
    price: 180000,
    sku: "CAS-5W30-SYN",
    description: "Aceite de motor avanzado 100% sintético con tecnología Fluid TITANIUM.",
    image: "/castrol.png",
    images: [{ url: "/castrol.png", alt: "Castrol EDGE 5W-30", isMain: true }],
    inStock: true,
    stock: 45,
  },
  {
    id: "liqui-moly-mos2-10w40",
    name: "Liqui Moly MoS2 Leichtlauf 10W-40",
    slug: "liqui-moly-mos2-10w40",
    category: { name: "Lubricantes Gasolina", slug: "lubricantes-gasolina" },
    brand: { name: "Liqui Moly", slug: "liqui-moly" },
    price: 160000,
    sku: "LM-10W40-MOS2",
    description: "Aceite de motor semisintético con disulfuro de molibdeno para máxima protección.",
    image: "/liquimoly.png",
    images: [{ url: "/liquimoly.png", alt: "Liqui Moly 10W40", isMain: true }],
    inStock: true,
    stock: 30,
  },
  {
    id: "terpel-oiltec-20w50",
    name: "Terpel Oiltec 20W-50 Titanio",
    slug: "terpel-oiltec-20w50",
    category: { name: "Lubricantes Gasolina", slug: "lubricantes-gasolina" },
    brand: { name: "Terpel", slug: "terpel" },
    price: 75000,
    sku: "TER-20W50-TIT",
    description: "Aceite mineral premium desarrollado para las condiciones del parque automotor colombiano.",
    image: "/12_terpel_oiltec_10w40_titanio.png",
    images: [{ url: "/12_terpel_oiltec_10w40_titanio.png", alt: "Terpel Oiltec 20W-50", isMain: true }],
    inStock: true,
    stock: 60,
  },

  // TRANSMISIÓN Y MANDOS
  {
    id: "motul-motylgear-75w90",
    name: "Motul Motylgear 75W-90",
    slug: "motul-motylgear-75w90",
    category: { name: "Transmisión", slug: "transmision" },
    brand: { name: "Motul", slug: "motul" },
    price: 95000,
    sku: "MOT-75W90-GEAR",
    description: "Lubricante Technosynthese para cajas de velocidades manuales y diferenciales.",
    image: "/transmision.png",
    images: [{ url: "/transmision.png", alt: "Motul Motylgear 75W-90", isMain: true }],
    inStock: true,
    stock: 25,
  },
  {
    id: "valvoline-high-performance-80w90-gl5",
    name: "Valvoline High Performance Gear Oil SAE 80W-90 API GL-5",
    slug: "valvoline-high-performance-gear-oil-80w90-gl5-946ml",
    category: { name: "Transmisión", slug: "transmision" },
    brand: { name: "Valvoline", slug: "valvoline" },
    price: 44508,
    sku: "M0536",
    shortDesc: "Valvulina mineral de extrema presión para engranajes y diferenciales que exijan SAE 80W-90 API GL-5.",
    description: "Aceite Valvoline High Performance SAE 80W-90 API GL-5 para diferenciales hipoides convencionales, transmisiones manuales no sincronizadas, cajas de dirección, mandos finales y tomas de fuerza donde el fabricante especifique esta viscosidad y nivel de servicio. Presentación de 1 cuarto US (0,946 L). No debe elegirse solo por marca del vehículo: confirmar manual, tipo de diferencial y presencia de sincronizadores o deslizamiento limitado.",
    image: "/catalogo-mantenimiento/valvoline-high-performance-80w90-gl5.png",
    images: [{ url: "/catalogo-mantenimiento/valvoline-high-performance-80w90-gl5.png", alt: "Valvoline High Performance SAE 80W-90 API GL-5", isMain: true }],
    attributes: [
      { id: "valv8090-1", name: "Viscosidad y desempeño", value: "SAE 80W-90 · API GL-5" },
      { id: "valv8090-2", name: "Aplicaciones", value: "Diferenciales hipoides convencionales y transmisiones manuales no sincronizadas" },
      { id: "valv8090-3", name: "Marcas compatibles", value: "Multimarca: Chevrolet, Ford, Toyota, Nissan, Mazda, Mitsubishi, Isuzu y otras, únicamente si el manual exige SAE 80W-90 API GL-5" },
      { id: "valv8090-4", name: "Modelos orientativos", value: "Pickups, SUV, vans y camiones; Hilux, D-Max, BT-50, Ranger y Frontier solo en versiones cuyo manual confirme 80W-90 GL-5" },
      { id: "valv8090-5", name: "Presentación", value: "1 U.S. qt · 0,946 L" },
      { id: "valv8090-6", name: "Fuente técnica", value: "Valvoline High Performance Gear Oil — ficha oficial" },
    ],
    inStock: true,
    stock: 1,
  },

  // ACEITES HIDRÁULICOS
  {
    id: "chevron-ursa-hydraulic-68",
    name: "Chevron Hydraulic Oil AW 68",
    slug: "chevron-ursa-hydraulic-68",
    category: { name: "Aceites Hidráulicos", slug: "hidraulico" },
    brand: { name: "Chevron", slug: "chevron" },
    price: 85000,
    sku: "CHV-AW68-HYD",
    description: "Fluido hidráulico antidesgaste para sistemas hidráulicos y bombas de alta presión.",
    image: "/chevron.png",
    images: [{ url: "/chevron.png", alt: "Chevron AW 68", isMain: true }],
    inStock: true,
    stock: 20,
  },

  // REFRIGERANTES / COOLANT
  {
    id: "total-glacelf-coolant",
    name: "TotalEnergies Glacelf Auto Supra Coolant",
    slug: "total-glacelf-coolant",
    category: { name: "Refrigerantes", slug: "coolant" },
    brand: { name: "TotalEnergies", slug: "totalenergies" },
    price: 55000,
    sku: "TOT-GLACELF-COOL",
    description: "Anticongelante y refrigerante de larga vida (OAT) para protección del radiador.",
    image: "/coolant.png",
    images: [{ url: "/coolant.png", alt: "Coolant TotalEnergies", isMain: true }],
    inStock: true,
    stock: 40,
  },
  {
    id: "starfree-refrigerante-rojo-galon",
    name: "Refrigerante Rojo Star Free Anticorrosivo Galón",
    slug: "refrigerante-rojo-star-free-galon-3785l",
    category: { name: "Refrigerantes", slug: "coolant" },
    brand: { name: "Star Free", slug: "star-free" },
    price: 34729,
    sku: "STARFREE-REF-ROJO-GAL",
    shortDesc: "Refrigerante rojo anticorrosivo y antioxidante para vehículos livianos, camionetas y camiones.",
    description: "Refrigerante rojo Star Free anticorrosivo y antioxidante para sistemas de enfriamiento. Presentación de 1 galón US (3,785 litros). Ayuda al control de la corrosión y el recalentamiento. El color por sí solo no determina compatibilidad: antes de mezclar o reemplazar se debe confirmar en el manual la tecnología, concentración y especificación admitidas por cada vehículo.",
    image: "/catalogo-mantenimiento/star-free-refrigerante-rojo-galon.png",
    images: [{ url: "/catalogo-mantenimiento/star-free-refrigerante-rojo-galon.png", alt: "Refrigerante rojo Star Free anticorrosivo galón", isMain: true }],
    attributes: [
      { id: "starfree-1", name: "Tipo", value: "Refrigerante rojo anticorrosivo y antioxidante" },
      { id: "starfree-2", name: "Marcas compatibles", value: "Multimarca; Chevrolet, Renault, Mazda, Toyota, Nissan, Kia, Hyundai, Ford y otras solo cuando el manual admita esta tecnología de refrigerante" },
      { id: "starfree-3", name: "Modelos compatibles", value: "Automóviles, pickups, vans y camiones; validar año, motor, concentración y refrigerante previamente instalado" },
      { id: "starfree-4", name: "Presentación", value: "1 galón US · 3,785 L" },
      { id: "starfree-5", name: "Advertencia", value: "No mezclar únicamente por coincidencia de color" },
    ],
    inStock: true,
    stock: 30,
  },

  // NUEVAS LÍNEAS DE ALTA ROTACIÓN — referencias bajo cotización
  {
    id: "acdelco-bujia-familia",
    name: "Bujía ACDelco para Motor a Gasolina — Referencia según Vehículo",
    slug: "bujia-acdelco-motor-gasolina-referencia-vehiculo",
    category: { name: "Eléctrico y Encendido", slug: "electrico-y-encendido" },
    brand: { name: "ACDelco", slug: "acdelco" },
    price: 0,
    sku: "ACD-BUJIA-COT",
    shortDesc: "Bujía ACDelco; confirmar referencia por marca, modelo, año y motor.",
    description: "Bujía ACDelco para sistemas de encendido de motores a gasolina, alcohol, GNC o combustible dual. Produce la chispa que inicia la combustión y contribuye al rendimiento, consumo y control de emisiones. La geometría, grado térmico y luz cambian según el motor; se cotiza únicamente después de validar vehículo y motorización.",
    image: "/catalogo-nuevas-lineas/acdelco-bujia-catalogo.png",
    images: [{ url: "/catalogo-nuevas-lineas/acdelco-bujia-catalogo.png", alt: "Imagen de catálogo de bujía ACDelco", isMain: true }],
    attributes: [
      { id: "acdbujia-1", name: "Aplicación", value: "Gasolina, alcohol, GNC y combustible dual" },
      { id: "acdbujia-2", name: "Selección", value: "Por marca, modelo, año y motor" },
      { id: "acdbujia-3", name: "Fuente técnica", value: "ACDelco Colombia — línea Bujías" },
      { id: "acdbujia-4", name: "Imagen", value: "Representación de familia; no identifica un SKU específico" },
    ],
    inStock: false,
    stock: 0,
  },
  {
    id: "acdelco-bateria-familia",
    name: "Batería ACDelco Libre de Mantenimiento — Capacidad según Vehículo",
    slug: "bateria-acdelco-libre-mantenimiento-capacidad-vehiculo",
    category: { name: "Eléctrico y Encendido", slug: "electrico-y-encendido" },
    brand: { name: "ACDelco", slug: "acdelco" },
    price: 0,
    sku: "ACD-BAT-COT",
    shortDesc: "Batería de arranque ACDelco; validar caja, polaridad, CCA y capacidad.",
    description: "Batería automotriz ACDelco para arranque, iluminación y alimentación de los sistemas eléctricos y electrónicos. La capacidad, corriente de arranque, polaridad y dimensiones deben corresponder exactamente al vehículo; precio sujeto a diagnóstico y referencia.",
    image: "/catalogo-nuevas-lineas/acdelco-bateria-catalogo.png",
    images: [{ url: "/catalogo-nuevas-lineas/acdelco-bateria-catalogo.png", alt: "Imagen de catálogo de batería ACDelco", isMain: true }],
    attributes: [
      { id: "acdbat-1", name: "Función", value: "Arranque, iluminación y alimentación eléctrica" },
      { id: "acdbat-2", name: "Validar", value: "Capacidad, CCA, polaridad, base y dimensiones" },
      { id: "acdbat-3", name: "Fuente técnica", value: "ACDelco Colombia — línea Baterías" },
      { id: "acdbat-4", name: "Imagen", value: "Representación de familia; no identifica amperaje o SKU" },
    ],
    inStock: false,
    stock: 0,
  },
  {
    id: "osram-ledriving-hl-bright-h4-h19",
    name: "OSRAM LEDriving HL BRIGHT H4/H19 12 V — 64193DWBRT",
    slug: "osram-ledriving-hl-bright-h4-h19-64193dwbrt",
    category: { name: "Eléctrico y Encendido", slug: "electrico-y-encendido" },
    brand: { name: "OSRAM", slug: "osram" },
    price: 0,
    sku: "64193DWBRT",
    shortDesc: "Par LED retrofit H4/H19 con base P43t (15/15 W, 6000 K, 1400/1100 lm).",
    description: "OSRAM LEDriving HL BRIGHT H4/H19 para luces altas y bajas en sistemas de 12 V. Base P43t, luz blanca 6000 K, 1400/1100 lm y vida útil de 5000 h.",
    image: "/catalogo-ktx-osram/osram-ledriving-hl-bright-h4.webp",
    images: [{ url: "/catalogo-ktx-osram/osram-ledriving-hl-bright-h4.webp", alt: "OSRAM LEDriving HL BRIGHT H4 H19 con marca REMBERT", isMain: true }],
    attributes: [
      { id: "osramh4-1", name: "Referencia", value: "64193DWBRT" },
      { id: "osramh4-2", name: "Base y sistema", value: "H4/H19 · P43t · 12 V" },
      { id: "osramh4-3", name: "Datos eléctricos", value: "15/15 W · 6000 K · 1400/1100 lm" },
      { id: "osramh4-4", name: "Compatibilidad", value: "Multimarca con bombillo H4/H19 P43t" },
      { id: "osramh4-5", name: "Fuente técnica", value: "OSRAM Automotive — LEDriving HL BRIGHT" },
    ],
    inStock: false,
    stock: 0,
  },
  {
    id: "gates-powergrip-kit-distribucion-bomba",
    name: "Kit de Distribución Gates PowerGrip con Bomba de Agua",
    slug: "kit-distribucion-gates-powergrip-bomba-agua",
    category: { name: "Motor y Distribución", slug: "motor-y-distribucion" },
    brand: { name: "Gates", slug: "gates" },
    price: 0,
    sku: "GATES-TCKWP-COT",
    shortDesc: "Solución completa Gates; contenido y referencia varían por motor.",
    description: "Familia de kits Gates PowerGrip para mantenimiento del sistema de distribución. Según aplicación puede incluir correa dentada, tensor, poleas, bomba de agua y herrajes. Gates recomienda sustituir la bomba accionada por distribución junto con la correa para reducir retrabajos y conservar el desempeño del sistema.",
    image: "/catalogo-nuevas-lineas/gates-kit-distribucion-bomba-agua-catalogo.png",
    images: [{ url: "/catalogo-nuevas-lineas/gates-kit-distribucion-bomba-agua-catalogo.png", alt: "Imagen de catálogo de kit de distribución Gates PowerGrip", isMain: true }],
    attributes: [
      { id: "gateskit-1", name: "Contenido típico", value: "Correa, tensor, poleas, bomba de agua y herrajes" },
      { id: "gateskit-2", name: "Selección", value: "Por motor, año y código de aplicación" },
      { id: "gateskit-3", name: "Fuente técnica", value: "Gates — Timing Belt Component Kits with Water Pumps" },
      { id: "gateskit-4", name: "Imagen", value: "Representación de familia; el contenido exacto cambia por SKU" },
    ],
    inStock: false,
    stock: 0,
  },
  {
    id: "luk-repset-620-1080-00",
    name: "Kit de Embrague LuK RepSet 620 1080 00",
    slug: "kit-embrague-luk-repset-620-1080-00",
    category: { name: "Embrague", slug: "embrague" },
    brand: { name: "LuK", slug: "luk" },
    price: 0,
    sku: "LUK-6201080000",
    shortDesc: "Prensa, disco y rodamiento; validar aplicación Renault/Dacia/Nissan/Lada.",
    description: "Kit de embrague LuK RepSet 620 1080 00. La ficha oficial incluye prensa 120 0201 10, disco 320 0467 10 y rodamiento de desembrague 500 0758 10. Cuenta con aplicaciones Dacia, Lada, Nissan y Renault, sujetas a confirmación por VIN y número OE.",
    image: "/catalogo-nuevas-lineas/luk-repset-kit-embrague-catalogo.png",
    images: [{ url: "/catalogo-nuevas-lineas/luk-repset-kit-embrague-catalogo.png", alt: "Imagen de catálogo de kit de embrague LuK RepSet", isMain: true }],
    attributes: [
      { id: "luk620-1", name: "Referencia", value: "620 1080 00" },
      { id: "luk620-2", name: "Contenido", value: "Prensa, disco y rodamiento de desembrague" },
      { id: "luk620-3", name: "EAN", value: "4005108035295" },
      { id: "luk620-4", name: "Fuente técnica", value: "Schaeffler Vehicle Lifetime Solutions" },
      { id: "luk620-5", name: "Imagen", value: "Representación comercial de la familia LuK RepSet" },
    ],
    inStock: false,
    stock: 0,
  },
  {
    id: "ktx-kit-embrague-familia",
    name: "Kit de Embrague KTX Clutch Parts — Referencia según Vehículo",
    slug: "kit-embrague-ktx-clutch-parts-referencia-vehiculo",
    category: { name: "Embrague", slug: "embrague" },
    brand: { name: "KTX", slug: "ktx" },
    price: 0,
    sku: "KTX-CLUTCH-COT",
    shortDesc: "Kit KTX con disco, prensa y rodamiento bajo cotización y confirmación por VIN.",
    description: "Kits de embrague KTX Clutch Parts con disco, prensa y rodamiento. Aplicación sujeta a confirmación por modelo, motor y transmisión.",
    image: "/catalogo-ktx-osram/ktx-kit-embrague-familia.webp",
    images: [{ url: "/catalogo-ktx-osram/ktx-kit-embrague-familia.webp", alt: "Kit de embrague KTX Clutch Parts con marca REMBERT", isMain: true }],
    attributes: [
      { id: "ktxclutch-1", name: "Contenido", value: "Disco, prensa y rodamiento de desembrague" },
      { id: "ktxclutch-2", name: "Validación", value: "Confirmar por VIN, modelo, año y motor" },
      { id: "ktxclutch-3", name: "Disponibilidad", value: "Bajo pedido y cotización" },
    ],
    inStock: false,
    stock: 0,
  },
  {
    id: "skf-kit-rodamiento-rueda-familia",
    name: "Kit de Rodamiento de Rueda SKF — Referencia según Vehículo",
    slug: "kit-rodamiento-rueda-skf-referencia-vehiculo",
    category: { name: "Rodamientos y Tracción", slug: "rodamientos-y-traccion" },
    brand: { name: "SKF", slug: "skf" },
    price: 0,
    sku: "SKF-VKBA-COT",
    shortDesc: "Kit SKF sellado y lubricado; validar generación, eje y sistema ABS.",
    description: "Familia de kits de rodamiento de rueda SKF para vehículos livianos. Según aplicación pueden incluir rodamiento, cubo, tuerca, circlip, pernos o anillo impulsor ABS. Los rodamientos están sellados y lubricados para su vida útil; la generación y el contenido del kit deben confirmarse por vehículo y posición.",
    image: "/catalogo-nuevas-lineas/skf-kit-rodamiento-catalogo.png",
    images: [{ url: "/catalogo-nuevas-lineas/skf-kit-rodamiento-catalogo.png", alt: "Imagen de catálogo de kit de rodamiento SKF", isMain: true }],
    attributes: [
      { id: "skfkit-1", name: "Diseños", value: "Generaciones HBU1, HBU2 y HBU3 según aplicación" },
      { id: "skfkit-2", name: "Validar", value: "Eje, posición, medidas, cubo y sistema ABS" },
      { id: "skfkit-3", name: "Fuente técnica", value: "SKF Automotive — Wheel Bearing Kits" },
      { id: "skfkit-4", name: "Imagen", value: "Representación de familia; componentes variables por SKU" },
    ],
    inStock: false,
    stock: 0,
  },

  // FRENOS Y SUSPENSIÓN
  {
    id: "motul-dot-4",
    name: "Motul DOT 4 Brake Fluid",
    slug: "motul-dot-4",
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: "Motul", slug: "motul" },
    price: 38000,
    sku: "MOT-DOT4-BRAKE",
    description: "Líquido de frenos sintético 100% poliglicol para sistemas hidráulicos y ABS.",
    image: "/frenos-liq.webp",
    images: [{ url: "/frenos-liq.webp", alt: "Líquido Frenos DOT 4", isMain: true }],
    inStock: true,
    stock: 50,
  },
  {
    id: "cofre-liquido-frenos-dot3-900",
    name: "Líquido para Frenos Cofre DOT 3 — 900 cm³",
    slug: "liquido-frenos-cofre-dot3-900cm3",
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: "Cofre", slug: "cofre" },
    price: 38913,
    sku: "LF028",
    shortDesc: "Líquido DOT 3 para sistemas de freno de disco y campana; presentación de 900 cm³.",
    description: "Líquido para frenos Cofre DOT 3 recomendado por el fabricante para sistemas de disco y campana. La ficha oficial indica cumplimiento de DOT 3, NTC 1703, FMVSS 116, SAE J1703, ISO 4925 y JIS K2233. Utilizar únicamente cuando el manual del vehículo autorice DOT 3 y evitar contaminación con aceite mineral, agua o líquido DOT 5 a base de silicona.",
    image: "/catalogo-mantenimiento/cofre-liquido-frenos-dot3-900cm3.webp",
    images: [{ url: "/catalogo-mantenimiento/cofre-liquido-frenos-dot3-900cm3.webp", alt: "Líquido para frenos Cofre DOT 3 de 900 cm³", isMain: true }],
    attributes: [
      { id: "cofredot3-1", name: "Especificación", value: "DOT 3 · NTC 1703 · FMVSS 116 · SAE J1703 · ISO 4925 · JIS K2233" },
      { id: "cofredot3-2", name: "Sistema", value: "Frenos hidráulicos de disco y campana" },
      { id: "cofredot3-3", name: "Marcas compatibles", value: "Multimarca: Chevrolet, Renault, Mazda, Hyundai, Kia, Nissan, Toyota y otras únicamente cuando el manual autorice DOT 3" },
      { id: "cofredot3-4", name: "Modelos compatibles", value: "Vehículos livianos y utilitarios con sistema hidráulico DOT 3; la compatibilidad cambia por año, versión y tipo de ABS" },
      { id: "cofredot3-5", name: "Presentación", value: "900 cm³" },
      { id: "cofredot3-6", name: "Fuente técnica", value: "Cofre — Líquido para frenos DOT 3" },
    ],
    inStock: true,
    stock: 1,
  },
  ...[
    {
      id: "frasle-pd1483-renault-logan-sandero", reference: "PD/1483",
      name: "Pastillas Delanteras Fras-le PD/1483 — Renault Logan / Sandero",
      slug: "pastillas-delanteras-frasle-pd1483-renault-logan-sandero-gasolina",
      vehicleBrands: "Renault", models: "Logan, Sandero y Stepway", years: "Logan 2015–2020; Sandero 2012–2020; Stepway 2014–2020",
      fitments: [
        { make: "Renault", model: "Logan", years: "2015–2020", position: "eje delantero" },
        { make: "Renault", model: "Sandero", years: "2012–2020", position: "eje delantero" },
        { make: "Renault", model: "Stepway", years: "2014–2020", position: "eje delantero" },
      ],
      oe: "410605612R", source: "Fras-le — lanzamiento oficial PD/1483 y catálogo de aplicaciones",
    },
    {
      id: "frasle-p1365-nissan-march-versa", reference: "P-1365",
      name: "Pastillas Delanteras Fras-le P-1365 — Nissan March / Versa",
      slug: "pastillas-delanteras-frasle-p1365-nissan-march-versa-gasolina",
      vehicleBrands: "Nissan", models: "March y Versa", years: "desde 2012",
      engine: "1.0 o 1.6 gasolina según versión", oe: "D10601HJ0A",
      fitments: [
        { make: "Nissan", model: "March", years: "desde 2012", engine: "1.0 o 1.6 gasolina según versión", position: "eje delantero" },
        { make: "Nissan", model: "Versa", years: "desde 2012", engine: "1.6 gasolina", position: "eje delantero" },
      ],
      source: "Fras-le/Lonaflex — boletín oficial de aplicaciones de pastillas",
    },
    {
      id: "frasle-pd1438-toyota-yaris-etios", reference: "PD/1438-CMAXX",
      name: "Pastillas Delanteras Fras-le Ceramaxx PD/1438-CMAXX — Toyota Yaris / Etios",
      slug: "pastillas-delanteras-frasle-pd1438-toyota-yaris-etios-gasolina",
      vehicleBrands: "Toyota", models: "Yaris, Etios, Etios Sedán y Etios Cross", years: "2012–2023",
      engine: "1.3 o 1.5 gasolina según modelo",
      fitments: [
        { make: "Toyota", model: "Yaris", years: "2012–2023 según versión", engine: "1.3 o 1.5 gasolina", position: "eje delantero" },
        { make: "Toyota", model: "Etios", years: "2012–2023", engine: "1.3 o 1.5 gasolina", position: "eje delantero" },
        { make: "Toyota", model: "Etios Sedán", years: "2012–2023", engine: "1.5 gasolina", position: "eje delantero" },
        { make: "Toyota", model: "Etios Cross", years: "2012–2023", engine: "1.5 gasolina", position: "eje delantero" },
      ],
      source: "Fras-le — portafolio oficial Ceramaxx 2024/2025",
    },
    {
      id: "frasle-pd1696-chevrolet-onix", reference: "PD/1696-CMAXX",
      name: "Pastillas Delanteras Fras-le Ceramaxx PD/1696-CMAXX — Chevrolet Onix / Onix Plus",
      slug: "pastillas-delanteras-frasle-pd1696-chevrolet-onix-plus-gasolina",
      vehicleBrands: "Chevrolet", models: "Onix y Onix Plus", years: "2019–2024",
      engine: "1.0 o 1.0 Turbo", oe: "26312031",
      fitments: [
        { make: "Chevrolet", model: "Onix", years: "2019–2024", engine: "1.0 o 1.0 Turbo según versión", position: "eje delantero" },
        { make: "Chevrolet", model: "Onix Plus", years: "2019–2024", engine: "1.0 o 1.0 Turbo según versión", position: "eje delantero" },
      ],
      source: "Fras-le — boletín oficial de lanzamientos 2024",
    },
    {
      id: "frasle-pd58-volkswagen-gol-saveiro", reference: "PD/58-CMAXX",
      name: "Pastillas Delanteras Fras-le Ceramaxx PD/58-CMAXX — Volkswagen Gol / Saveiro / Fox",
      slug: "pastillas-delanteras-frasle-pd58-volkswagen-gol-saveiro-fox-gasolina",
      vehicleBrands: "Volkswagen", models: "Gol, Saveiro, Fox, SpaceFox y CrossFox", years: "2003–2021",
      fitments: [
        { make: "Volkswagen", model: "Gol", years: "2003–2021 según generación", position: "eje delantero" },
        { make: "Volkswagen", model: "Saveiro", years: "2003–2021 según generación", position: "eje delantero" },
        { make: "Volkswagen", model: "Fox", years: "2003–2021 según generación", position: "eje delantero" },
        { make: "Volkswagen", model: "SpaceFox", years: "2003–2021 según generación", position: "eje delantero" },
        { make: "Volkswagen", model: "CrossFox", years: "2003–2021 según generación", position: "eje delantero" },
      ],
      source: "Fras-le — boletín oficial de lanzamientos 2024",
    },
    {
      id: "frasle-pd2225-chevrolet-tracker-montana", reference: "PD/2225-CMAXX",
      name: "Pastillas Delanteras Fras-le Ceramaxx PD/2225-CMAXX — Chevrolet Tracker / Montana",
      slug: "pastillas-delanteras-frasle-pd2225-chevrolet-tracker-montana-gasolina",
      vehicleBrands: "Chevrolet", models: "Tracker y Montana", years: "2020–2024",
      fitments: [
        { make: "Chevrolet", model: "Tracker", years: "2020–2024", position: "eje delantero" },
        { make: "Chevrolet", model: "Montana", years: "2020–2024", position: "eje delantero" },
      ],
      source: "Fras-le — boletín oficial de lanzamientos 2024",
    },
    {
      id: "frasle-pd1386-renault-duster-captur", reference: "PD/1386",
      name: "Pastillas Delanteras Fras-le PD/1386 — Renault Duster / Captur Gasolina",
      slug: "pastillas-delanteras-frasle-pd1386-renault-duster-captur-gasolina",
      vehicleBrands: "Renault", models: "Duster y Captur", years: "desde 2011",
      engine: "1.6 gasolina exclusivamente",
      fitments: [
        { make: "Renault", model: "Duster", years: "desde 2011 según catálogo", engine: "1.6 gasolina", position: "eje delantero" },
        { make: "Renault", model: "Captur", years: "según mercado y versión", engine: "1.6 gasolina", position: "eje delantero" },
      ],
      source: "Fras-le — tabla oficial de aplicaciones con antirruido, edición enero de 2022",
    },
    {
      id: "frasle-pd1589-kia-sportage-hyundai-tucson", reference: "PD/1589",
      name: "Pastillas Delanteras Fras-le PD/1589 — Kia Sportage / Hyundai Tucson",
      slug: "pastillas-delanteras-frasle-pd1589-kia-sportage-hyundai-tucson-gasolina",
      vehicleBrands: "Kia / Hyundai", models: "Kia Sportage EX/LX y Hyundai New Tucson GL/GLS/LMT", years: "desde 2017",
      engine: "Sportage 2.0 o New Tucson 1.6 Turbo gasolina",
      fitments: [
        { make: "Kia", model: "Sportage", years: "desde 2017", engine: "2.0 gasolina", version: "EX/LX", position: "eje delantero" },
        { make: "Hyundai", model: "New Tucson", years: "desde 2017", engine: "1.6 Turbo gasolina", version: "GL/GLS/LMT", position: "eje delantero" },
      ],
      fmsi: "D1847", oe: "58101D7A10", source: "Fras-le — boletín oficial PD/1589, julio de 2020",
    },
    {
      id: "frasle-pd1348-hyundai-kia-cerato", reference: "PD/1348-CMAXX",
      name: "Pastillas Delanteras Fras-le Ceramaxx PD/1348-CMAXX — Hyundai / Kia",
      slug: "pastillas-delanteras-frasle-pd1348-hyundai-hb20-kia-cerato-gasolina",
      vehicleBrands: "Hyundai / Kia", models: "HB20, Veloster y Cerato", years: "2012–2022",
      fitments: [
        { make: "Hyundai", model: "HB20", years: "2012–2022 según versión", position: "eje delantero" },
        { make: "Hyundai", model: "Veloster", years: "2012–2022 según versión", position: "eje delantero" },
        { make: "Kia", model: "Cerato", years: "2012–2022 según versión", position: "eje delantero" },
      ],
      source: "Fras-le — portafolio oficial Ceramaxx 2024/2025",
    },
    {
      id: "frasle-pd1520-nissan-kicks", reference: "PD/1520-CMAXX",
      name: "Pastillas Delanteras Fras-le Ceramaxx PD/1520-CMAXX — Nissan Kicks",
      slug: "pastillas-delanteras-frasle-pd1520-nissan-kicks-gasolina",
      vehicleBrands: "Nissan", models: "Kicks gasolina", years: "2016–2023",
      fitments: [
        { make: "Nissan", model: "Kicks", years: "2016–2023", engine: "gasolina según versión", position: "eje delantero" },
      ],
      source: "Fras-le — boletín oficial de lanzamientos 2024",
    },
    {
      id: "frasle-pd1364-chevrolet-spark-gt", reference: "PD/1364",
      name: "Pastillas Delanteras Fras-le PD/1364 — Chevrolet Spark / Spark GT",
      slug: "pastillas-delanteras-frasle-pd1364-chevrolet-spark-gt-gasolina",
      vehicleBrands: "Chevrolet", models: "Spark y Spark GT", years: "Spark 2011–2016; Spark GT 2010–2016",
      fitments: [
        { make: "Chevrolet", model: "Spark", years: "2011–2016", position: "eje delantero" },
        { make: "Chevrolet", model: "Spark GT", years: "2010–2016", position: "eje delantero" },
      ],
      fmsi: "D1590", source: "Fras-le — catálogo oficial de pastillas para vehículos livianos",
    },
    {
      id: "frasle-pd1481-kia-picanto", reference: "PD/1481",
      name: "Pastillas Delanteras Fras-le PD/1481 — Kia Picanto",
      slug: "pastillas-delanteras-frasle-pd1481-kia-picanto-gasolina",
      vehicleBrands: "Kia", models: "Picanto y Picanto Ion", years: "2011–2020 en el catálogo consultado",
      fitments: [
        { make: "Kia", model: "Picanto", years: "2011–2020 en el catálogo consultado", position: "eje delantero" },
        { make: "Kia", model: "Picanto Ion", years: "2011–2020 en el catálogo consultado", position: "eje delantero" },
      ],
      oe: "581011YA00 / 581011YA30", source: "Fras-le — lanzamiento oficial PD/1481",
    },
  ].map((application) => brakeApplication({
    ...application,
    brand: "Fras-le",
    image: "/catalogo-frenos/fras-le-pastillas-familia.webp",
    axle: "Eje delantero",
  })),
  brakeApplication({
    id: "bosch-f002h26431-chevrolet-aveo-optra",
    name: "Pastillas Delanteras Bosch F 002 H26 431 — Chevrolet Aveo / Optra",
    slug: "pastillas-delanteras-bosch-f002h26431-chevrolet-aveo-optra-gasolina",
    brand: "Bosch", reference: "F 002 H26 431",
    image: "/catalogo-frenos/bosch-pastillas-familia.webp",
    vehicleBrands: "Chevrolet", models: "Aveo 1.4/1.6 y Optra 1.6/1.8/2.0 gasolina",
    years: "según mercado y versión", axle: "Eje delantero",
    fitmentStatus: "conditional",
    source: "Bosch — catálogo internacional oficial de sistemas de freno; confirmar equivalencia para Colombia",
  }),
  brakeApplication({
    id: "bosch-f002h26418-chevrolet-spark-matiz",
    name: "Zapatas Traseras Bosch F 002 H26 418 — Chevrolet Spark / Daewoo Matiz",
    slug: "zapatas-traseras-bosch-f002h26418-chevrolet-spark-daewoo-matiz-gasolina",
    brand: "Bosch", reference: "F 002 H26 418",
    image: "/catalogo-frenos/bosch-zapatas-familia.webp",
    vehicleBrands: "Chevrolet / Daewoo", models: "Spark 1.0 gasolina y Matiz 0.8 gasolina",
    years: "según mercado y versión", axle: "Eje trasero · freno de tambor",
    fitmentStatus: "conditional",
    source: "Bosch — catálogo internacional oficial de sistemas de freno; confirmar diámetro para Colombia",
  }),
  brakeApplication({
    id: "bosch-f002h26419-chevrolet-aveo",
    name: "Zapatas Traseras Bosch F 002 H26 419 — Chevrolet Aveo",
    slug: "zapatas-traseras-bosch-f002h26419-chevrolet-aveo-gasolina",
    brand: "Bosch", reference: "F 002 H26 419",
    image: "/catalogo-frenos/bosch-zapatas-familia.webp",
    vehicleBrands: "Chevrolet", models: "Aveo 1.2/1.4/1.6 gasolina",
    years: "según mercado y versión", axle: "Eje trasero · freno de tambor",
    fitmentStatus: "conditional",
    source: "Bosch — catálogo internacional oficial de sistemas de freno; confirmar diámetro para Colombia",
  }),
  {
    id: "incolbest-pastillas-delanteras",
    name: "Pastillas de Freno Delanteras Incolbest — Referencia según Vehículo",
    slug: "incolbest-pastillas-delanteras",
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: "Incolbest", slug: "incolbest" },
    price: 0,
    sku: "INC-PAD-FRONT",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Familia visual Incolbest; la forma de la pastilla no determina por sí sola una aplicación.",
    fitmentRequirements: ["VIN", "marca", "modelo", "año", "motor", "eje", "sistema de freno", "referencia OE o muestra"],
    fitmentSource: "Catálogo Incolbest; referencia exacta pendiente de identificación por vehículo",
    description: "Familia de pastillas delanteras Incolbest. La referencia exacta se selecciona por vehículo, eje, mordaza y sistema de freno; no se ofrece como pieza universal.",
    image: "/incolbest-pastillas-menu.webp",
    images: [{ url: "/incolbest-pastillas-menu.webp", alt: "Pastillas Incolbest", isMain: true }],
    inStock: false,
    stock: 0,
  },
  {
    id: "incolbest-discos-freno",
    name: "Discos de Freno Incolbest — Referencia según Vehículo",
    slug: "incolbest-discos-freno",
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: "Incolbest", slug: "incolbest" },
    price: 0,
    sku: "INC-ROTOR-VENT",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Familia visual Incolbest; un disco debe coincidir en diámetro, espesor, altura, número de pernos y eje.",
    fitmentRequirements: ["VIN", "marca", "modelo", "año", "motor", "eje", "diámetro", "espesor", "altura", "patrón de pernos", "referencia OE"],
    fitmentSource: "Catálogo Incolbest; referencia exacta pendiente de identificación por vehículo",
    description: "Familia de discos de freno Incolbest. La referencia debe validarse por dimensiones, eje, maza y sistema ABS; la imagen no representa una pieza universal.",
    image: "/incolbest-discos-menu.webp",
    images: [{ url: "/incolbest-discos-menu.webp", alt: "Discos Incolbest", isMain: true }],
    inStock: false,
    stock: 0,
  },
  {
    id: "gabriel-amortiguador-gas",
    name: "Amortiguador Gabriel Gas-Matic — Referencia según Vehículo",
    slug: "gabriel-amortiguador-gas",
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: "Gabriel", slug: "gabriel" },
    price: 0,
    sku: "GAB-GAS-FRONT",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Familia visual Gabriel; lado, eje, carrocería, suspensión y anclajes cambian la referencia.",
    fitmentRequirements: ["VIN", "marca", "modelo", "año", "motor", "carrocería", "eje", "lado", "tipo de suspensión", "referencia OE"],
    fitmentSource: "Catálogo Gabriel; referencia exacta pendiente de identificación por vehículo",
    description: "Familia de amortiguadores Gabriel Gas-Matic. La aplicación se confirma por VIN, eje, lado, anclajes y configuración de suspensión; no se vende por semejanza visual.",
    image: "/catalogo-proveedores/gabriel-amortiguador-automovil-referencia-vin.jpg",
    images: [{ url: "/catalogo-proveedores/gabriel-amortiguador-automovil-referencia-vin.jpg", alt: "Amortiguador Gabriel", isMain: true }],
    imageStatus: "ai-catalog-watermarked",
    inStock: false,
    stock: 0,
  },

  // DIRECCIÓN, SUSPENSIÓN Y FRENO HIDRÁULICO — COTIZACIÓN VALIDADA POR VIN
  ...brandPanelProducts,
  ...frenosSuspensionProducts,
  ...catalogoProveedoresProducts,

  // FILTROS
  {
    id: "wix-wl7570-filtro-aceite",
    name: "Filtro de Aceite WIX WL7570",
    slug: "wix-wl7570-filtro-aceite",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "WIX Filters", slug: "wix" },
    price: 32000,
    sku: "WIX-WL7570",
    description: "Filtro de aceite blindado para máxima retención de impurezas y flujo de lubricante.",
    image: "/01_wix_wl7570_filtro_aceite.png",
    images: [{ url: "/01_wix_wl7570_filtro_aceite.png", alt: "Filtro WIX WL7570", isMain: true }],
    inStock: true,
    stock: 75,
  },
  {
    id: "wix-wa9906-filtro-aire",
    name: "Filtro de Aire WIX WA9906 Panel",
    slug: "wix-wa9906-filtro-aire",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "WIX Filters", slug: "wix" },
    price: 45000,
    sku: "WIX-WA9906",
    description: "Filtro de aire tipo panel de alta eficiencia para admisión del motor.",
    image: "/02_wix_wa9906_filtro_aire.png",
    images: [{ url: "/02_wix_wa9906_filtro_aire.png", alt: "Filtro Aire WIX", isMain: true }],
    inStock: true,
    stock: 40,
  },
  {
    id: "auto-coexito-filtro-cabina",
    name: "Filtro de Cabina / Habitáculo Coéxito",
    slug: "auto-coexito-filtro-cabina",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "Coéxito", slug: "coexito" },
    price: 38000,
    sku: "COX-COAC-305",
    description: "Filtro antipolen para aire acondicionado y purificación de aire en cabina.",
    image: "/07_auto_coexito_coac_305_filtro_cabina.png",
    images: [{ url: "/07_auto_coexito_coac_305_filtro_cabina.png", alt: "Filtro Cabina Coéxito", isMain: true }],
    inStock: true,
    stock: 30,
  },
  {
    id: "filtro-aceite-gasolina-multimarca",
    name: "Filtro de Aceite para Autos a Gasolina Multimarca",
    slug: "filtro-aceite-gasolina-multimarca",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "WIX Filters", slug: "wix" },
    price: 0,
    sku: "FIL-ACE-GAS-MULTI",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Familia de filtros de aceite; cada motor exige una referencia, rosca, válvula y dimensiones concretas.",
    fitmentRequirements: ["VIN", "motor", "rosca", "diámetro", "altura", "válvula bypass y antirretorno", "referencia OE"],
    description: "Familia de filtros de aceite para automóviles a gasolina. No es un filtro único para todas las marcas: se cotiza la referencia exacta por VIN, motor, dimensiones y número OE.",
    image: "/filtro-aceite-gasolina-catalogo.png",
    images: [{ url: "/filtro-aceite-gasolina-catalogo.png", alt: "Filtro de aceite para autos a gasolina", isMain: true }],
    inStock: false,
    stock: 0,
  },
  {
    id: "filtro-aire-gasolina-multimarca",
    name: "Filtro de Aire para Autos a Gasolina Multimarca",
    slug: "filtro-aire-gasolina-multimarca",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "WIX Filters", slug: "wix" },
    price: 0,
    sku: "FIL-AIR-GAS-MULTI",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Familia de filtros de aire; la forma, largo, ancho y sello cambian por modelo, motor y caja del filtro.",
    fitmentRequirements: ["VIN", "motor", "medidas del elemento", "forma", "referencia OE"],
    description: "Familia de filtros de aire tipo panel para vehículos a gasolina. Los modelos enumerados en el catálogo usan referencias diferentes; confirmar VIN, motor, forma y medidas.",
    image: "/filtro-aire-gasolina-catalogo.png",
    images: [{ url: "/filtro-aire-gasolina-catalogo.png", alt: "Filtro de aire para autos a gasolina", isMain: true }],
    inStock: false,
    stock: 0,
  },
  {
    id: "filtro-combustible-gasolina-multimarca",
    name: "Filtro de Combustible para Autos a Gasolina",
    slug: "filtro-combustible-gasolina-multimarca",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "Bosch", slug: "bosch" },
    price: 0,
    sku: "FIL-COMB-GAS-MULTI",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Familia de filtros de combustible gasolina; presión, caudal, conexiones y ubicación varían por sistema de inyección.",
    fitmentRequirements: ["VIN", "motor", "presión del sistema", "conectores", "sentido de flujo", "referencia OE"],
    description: "Familia de filtros para sistemas de gasolina. No aplica a diésel y no corresponde a una referencia universal; validar presión, conectores, ubicación y referencia OE.",
    image: "/filtro-combustible-gasolina-catalogo.png",
    images: [{ url: "/filtro-combustible-gasolina-catalogo.png", alt: "Filtro de combustible para autos a gasolina", isMain: true }],
    inStock: false,
    stock: 0,
  },
  {
    id: "filtro-cabina-gasolina-multimarca",
    name: "Filtro de Cabina para Autos a Gasolina Multimarca",
    slug: "filtro-cabina-gasolina-multimarca",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "Coéxito", slug: "coexito" },
    price: 0,
    sku: "FIL-CAB-GAS-MULTI",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Familia de filtros de cabina; medidas, orientación del flujo y acceso cambian por plataforma y año.",
    fitmentRequirements: ["VIN", "año", "carrocería", "medidas", "sentido de flujo", "referencia OE"],
    description: "Familia de filtros de habitáculo estándar o de carbón activado. Cada plataforma usa medidas y orientación específicas; validar VIN y referencia OE.",
    image: "/filtro-cabina-gasolina-catalogo.png",
    images: [{ url: "/filtro-cabina-gasolina-catalogo.png", alt: "Filtro de cabina para autos a gasolina", isMain: true }],
    inStock: false,
    stock: 0,
  },

  // SILICONAS Y SELLANTES AUTOMOTRICES — marca exclusiva Victor Reinz
  {
    id: "victor-reinz-reinzosil-70ml",
    name: "Victor Reinz REINZOSIL Sellante Universal Antracita 70 ml",
    slug: "victor-reinz-reinzosil-sellante-universal-70ml",
    category: { name: "Siliconas y Sellantes", slug: "siliconas" },
    brand: { name: "Victor Reinz", slug: "victor-reinz" },
    price: 0,
    sku: "VR-REINZOSIL-70ML",
    description: "Compuesto sellante universal antracita permanentemente elástico para formar y reparar juntas en motores, cajas, bombas y carcasas. Presentación de 70 ml, resistente a temperaturas de hasta +300 °C. Precio sujeto a cotización y disponibilidad.",
    image: "/catalogo-siliconas-automotrices/victor-reinz-reinzosil-70ml-original.png",
    images: [{ url: "/catalogo-siliconas-automotrices/victor-reinz-reinzosil-70ml-original.png", alt: "Victor Reinz REINZOSIL sellante universal antracita 70 ml", isMain: true }],
    inStock: true,
    stock: 20,
  },

  // GRASAS Y ADITIVOS
  {
    id: "mobil-grease-xhp-222",
    name: "Mobilgrease XHP 222 Complejo de Litio",
    slug: "mobil-grease-xhp-222",
    category: { name: "Grasas y Aditivos", slug: "grasas-y-aditivos" },
    brand: { name: "Mobil", slug: "mobil" },
    price: 35000,
    sku: "MOB-XHP222-GRS",
    description: "Grasa de complejo de litio para rodamientos, chasis y condiciones severas de carga.",
    image: "/caneca.png",
    images: [{ url: "/caneca.png", alt: "Mobilgrease XHP 222", isMain: true }],
    inStock: true,
    stock: 50,
  },

  // UREA AUTOMOTRIZ (DEF)
  {
    id: "urea-automotriz-def-5gal",
    name: "Urea Automotriz Grado Automotriz DEF / AdBlue",
    slug: "urea-automotriz-def-5gal",
    category: { name: "Urea Automotriz", slug: "urea" },
    brand: { name: "Coéxito", slug: "coexito" },
    price: 68000,
    sku: "DEF-UREA-5GAL",
    description: "Solución de urea al 32.5% de alta pureza para reducción catalítica selectiva SCR.",
    image: "/urea.png",
    images: [{ url: "/urea.png", alt: "Urea DEF Automotriz", isMain: true }],
    inStock: true,
    stock: 60,
  },

  // RADIADORES Y SISTEMA DE ENFRIAMIENTO
  {
    id: "radiador-chevrolet-luv-dmax-25",
    name: "Radiador Chevrolet LUV D-Max 2.5 Diésel",
    slug: "radiador-chevrolet-luv-dmax-25",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Chevrolet", slug: "chevrolet" },
    price: 520000,
    sku: "RAD-CHV-DMX-25",
    description: "Radiador de reemplazo para Chevrolet LUV D-Max 2.5 diésel. Aplicaciones 2WD/4WD; confirmar año, transmisión y VIN.",
    image: "/radiador-dmax-25.png",
    images: [{ url: "/radiador-dmax-25.png", alt: "Radiador Chevrolet LUV D-Max 2.5", isMain: true }],
    inStock: true,
    stock: 8,
  },
  {
    id: "radiador-chevrolet-luv-dmax-30",
    name: "Radiador Chevrolet LUV D-Max 3.0 Diésel",
    slug: "radiador-chevrolet-luv-dmax-30",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Chevrolet", slug: "chevrolet" },
    price: 560000,
    sku: "RAD-CHV-DMX-30",
    description: "Radiador de reemplazo para Chevrolet LUV D-Max 3.0 diésel, motores 4JH1. Confirmar configuración por VIN.",
    image: "/radiador-dmax-30.png",
    images: [{ url: "/radiador-dmax-30.png", alt: "Radiador Chevrolet LUV D-Max 3.0", isMain: true }],
    inStock: true,
    stock: 7,
  },
  {
    id: "radiador-chevrolet-colorado-s10",
    name: "Radiador Chevrolet Colorado / S10",
    slug: "radiador-chevrolet-colorado-s10",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Chevrolet", slug: "chevrolet" },
    price: 590000,
    sku: "RAD-CHV-COL-S10",
    description: "Radiador para pickup Chevrolet Colorado/S10. La aplicación cambia según motor, año y transmisión; confirmar por VIN.",
    image: "/radiador-colorado-s10.png",
    images: [{ url: "/radiador-colorado-s10.png", alt: "Radiador Chevrolet Colorado S10", isMain: true }],
    inStock: true,
    stock: 5,
  },
  {
    id: "radiador-renault-duster-oroch",
    name: "Radiador Renault Duster Oroch 1.6 / 2.0",
    slug: "radiador-renault-duster-oroch",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Renault", slug: "renault" },
    price: 430000,
    sku: "RAD-REN-OROCH",
    description: "Radiador de aluminio para Renault Duster Oroch 1.6 y 2.0. Confirmar versión, aire acondicionado y transmisión.",
    image: "/radiador-oroch.png",
    images: [{ url: "/radiador-oroch.png", alt: "Radiador Renault Duster Oroch", isMain: true }],
    inStock: true,
    stock: 6,
  },
  {
    id: "radiador-renault-alaskan-25",
    name: "Radiador Renault Alaskan 2.5 Diésel",
    slug: "radiador-renault-alaskan-25",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Renault", slug: "renault" },
    price: 850000,
    sku: "RAD-REN-ALASKAN-25",
    description: "Radiador de servicio pesado para Renault Alaskan 2.5 diésel. Confirmar 4x2/4x4, transmisión y año por VIN.",
    image: "/radiador-alaskan.png",
    images: [{ url: "/radiador-alaskan.png", alt: "Radiador Renault Alaskan 2.5", isMain: true }],
    inStock: true,
    stock: 3,
  },
  {
    id: "radiador-chevrolet-onix-tracker",
    name: "Radiador Chevrolet Spark GT / Beat 1.2L 16V",
    slug: "radiador-chevrolet-spark-gt-beat-12",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Chevrolet", slug: "chevrolet" },
    price: 299000,
    sku: "RAD-CHV-SPK-GT-96676341",
    description: "Radiador de aluminio para Chevrolet Spark GT / Beat M300 1.2L 16V, transmisión mecánica. Referencia OEM 96676341; confirmar compatibilidad por VIN antes de comprar.",
    image: "/radiador-spark-gt-frontal.png",
    images: [
      { url: "/radiador-spark-gt-frontal.png", alt: "Radiador Chevrolet Spark GT frontal", isMain: true },
      { url: "/radiador-spark-gt-angulo.png", alt: "Radiador Chevrolet Spark GT en ángulo", isMain: false },
      { url: "/radiador-spark-gt-detalle.png", alt: "Detalle del radiador Chevrolet Spark GT", isMain: false }
    ],
    inStock: true,
    stock: 15,
  },
  {
    id: "radiador-chevrolet-sail-14",
    name: "Radiador Chevrolet Sail / Aveo / Optra — Familia por Referencia",
    slug: "radiador-chevrolet-sail-14",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Chevrolet", slug: "chevrolet" },
    price: 0,
    sku: "RAD-CHV-SAIL-14",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Sail, Aveo y Optra no comparten un radiador universal; existen referencias diferentes por año, motor, transmisión y sistema de aire acondicionado.",
    fitmentRequirements: ["VIN", "año", "motor", "transmisión", "aire acondicionado", "medidas", "posición de bocas y soportes", "referencia OE"],
    description: "Familia de radiadores Chevrolet. Sail, Aveo y Optra requieren selección individual por VIN, motor, transmisión, medidas y referencia OE; no comparten una pieza entre todas sus generaciones.",
    image: "/radiador-banner.jpg",
    images: [{ url: "/radiador-banner.jpg", alt: "Radiador Chevrolet Sail 1.4", isMain: true }],
    inStock: false,
    stock: 0,
  },
  {
    id: "radiador-renault-duster-logan-sandero",
    name: "Radiador Renault Duster / Logan / Sandero / Stepway 1.6 - 2.0 16V",
    slug: "radiador-renault-duster-logan-sandero",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Renault", slug: "renault" },
    price: 0,
    sku: "RAD-REN-DUST-K4M",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Duster, Logan, Sandero y Stepway usan referencias distintas según plataforma, motor, transmisión y aire acondicionado.",
    fitmentRequirements: ["VIN", "motor K4M/H4M/F4R u otro", "año", "transmisión", "aire acondicionado", "medidas y bocas", "referencia OE"],
    description: "Familia de radiadores Renault. La mención de varios modelos no significa que la pieza sea intercambiable; se cotiza por VIN, código de motor, transmisión, medidas y referencia OE.",
    image: "/radiador-auto.jpg",
    images: [{ url: "/radiador-auto.jpg", alt: "Radiador Renault Duster Sandero", isMain: true }],
    inStock: false,
    stock: 0,
  },
  {
    id: "radiador-renault-kwid-clio-megane",
    name: "Radiador Renault Kwid 1.0 / Clio Campus / Megane / Symbol 1.4 - 1.6",
    slug: "radiador-renault-kwid-clio-megane",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Renault", slug: "renault" },
    price: 0,
    sku: "RAD-REN-KWD-CLIO",
    referenceType: "internal-quote",
    fitmentStatus: "family",
    fitmentSummary: "Kwid, Clio, Mégane y Symbol pertenecen a plataformas distintas y no usan un radiador común.",
    fitmentRequirements: ["VIN", "plataforma", "año", "motor", "transmisión", "aire acondicionado", "medidas y referencia OE"],
    description: "Familia de radiadores Renault para cotización. Kwid, Clio, Mégane y Symbol no deben agruparse como una pieza única: cada plataforma requiere una referencia específica.",
    image: "/radiador-banner.jpg",
    images: [{ url: "/radiador-banner.jpg", alt: "Radiador Renault Kwid Clio", isMain: true }],
    inStock: false,
    stock: 0,
  },
  {
    id: "acdelco-dex-cool-50-50-galon",
    name: "Líquido Refrigerante ACDelco DEX-COOL 50/50 Prediluido Galón (4L)",
    slug: "refrigerante-acdelco-dex-cool-50-50-galon-4l",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "ACDelco", slug: "acdelco" },
    price: 62000,
    sku: "ACD-DEXCOOL-88863336-4L",
    description: "Refrigerante y anticongelante original ACDelco DEX-COOL Extended Life 50/50 prediluido listo para usar (Galón / 4 Litros, Ref. GM 88863336). Fórmula OAT orgánica color naranja de larga duración (hasta 5 años o 240.000 km). Protección avanzada contra corrosión, ebullición y cavitación en radiadores de aluminio para Chevrolet, GM y vehículos multimarca.",
    image: "/acdelco-dex-cool-50-50-galon.png",
    images: [{ url: "/acdelco-dex-cool-50-50-galon.png", alt: "Refrigerante ACDelco DEX-COOL 50/50 Galón 4 Litros", isMain: true }],
    inStock: true,
    stock: 30,
  },
  {
    id: "tapa-radiador-presurizada-11-bar",
    name: "Tapa de Radiador Presurizada de Seguridad 1.1 Bar (16 PSI)",
    slug: "tapa-radiador-presurizada-11-bar",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Bosch", slug: "bosch" },
    price: 32000,
    sku: "CAP-RAD-11-BAR",
    description: "Tapa presurizada de acero inoxidable con sello de caucho sintético de alta temperatura y válvula de escape para control óptimo de presión del circuito de refrigeración.",
    image: "/coolant.png",
    images: [{ url: "/coolant.png", alt: "Tapa Radiador 1.1 Bar", isMain: true }],
    inStock: true,
    stock: 50,
  },
];

export const products = allProducts;

export function getProductById(id) {
  return products.find(p => p.id === id || p.slug === id);
}
