export const products = [
  // LUBRICANTES GASOLINA
  {
    id: "castrol-edge-5w30",
    name: "Castrol EDGE 5W-30 Sintético",
    slug: "castrol-edge-5w30",
    category: { name: "Lubricantes Gasolina", slug: "lubricantes-gasolina" },
    brand: { name: "Castrol", slug: "castrol" },
    price: 180000,
    sku: "CAS-5W30-SYN",
    description: "Aceite de motor avanzado 100% sintético con tecnología Fluid TITANIUM.",
    image: "/castrol.png",
    images: [{ url: "/castrol.png", alt: "Castrol EDGE 5W-30", isMain: true }],
    inStock: true,
    stock: 45,
  },
  {
    id: "liqui-moly-mos2-10w40",
    name: "Liqui Moly MoS2 Leichtlauf 10W-40",
    slug: "liqui-moly-mos2-10w40",
    category: { name: "Lubricantes Gasolina", slug: "lubricantes-gasolina" },
    brand: { name: "Liqui Moly", slug: "liqui-moly" },
    price: 160000,
    sku: "LM-10W40-MOS2",
    description: "Aceite de motor semisintético con disulfuro de molibdeno para máxima protección.",
    image: "/liquimoly.png",
    images: [{ url: "/liquimoly.png", alt: "Liqui Moly 10W40", isMain: true }],
    inStock: true,
    stock: 30,
  },
  {
    id: "terpel-oiltec-20w50",
    name: "Terpel Oiltec 20W-50 Titanio",
    slug: "terpel-oiltec-20w50",
    category: { name: "Lubricantes Gasolina", slug: "lubricantes-gasolina" },
    brand: { name: "Terpel", slug: "terpel" },
    price: 75000,
    sku: "TER-20W50-TIT",
    description: "Aceite mineral premium desarrollado para las condiciones del parque automotor colombiano.",
    image: "/12_terpel_oiltec_10w40_titanio.png",
    images: [{ url: "/12_terpel_oiltec_10w40_titanio.png", alt: "Terpel Oiltec 20W-50", isMain: true }],
    inStock: true,
    stock: 60,
  },

  // TRANSMISIÓN Y MANDOS
  {
    id: "motul-motylgear-75w90",
    name: "Motul Motylgear 75W-90",
    slug: "motul-motylgear-75w90",
    category: { name: "Transmisión", slug: "transmision" },
    brand: { name: "Motul", slug: "motul" },
    price: 95000,
    sku: "MOT-75W90-GEAR",
    description: "Lubricante Technosynthese para cajas de velocidades manuales y diferenciales.",
    image: "/transmision.png",
    images: [{ url: "/transmision.png", alt: "Motul Motylgear 75W-90", isMain: true }],
    inStock: true,
    stock: 25,
  },

  // ACEITES HIDRÁULICOS
  {
    id: "chevron-ursa-hydraulic-68",
    name: "Chevron Hydraulic Oil AW 68",
    slug: "chevron-ursa-hydraulic-68",
    category: { name: "Aceites Hidráulicos", slug: "hidraulico" },
    brand: { name: "Chevron", slug: "chevron" },
    price: 85000,
    sku: "CHV-AW68-HYD",
    description: "Fluido hidráulico antidesgaste para sistemas hidráulicos y bombas de alta presión.",
    image: "/chevron.png",
    images: [{ url: "/chevron.png", alt: "Chevron AW 68", isMain: true }],
    inStock: true,
    stock: 20,
  },

  // REFRIGERANTES / COOLANT
  {
    id: "total-glacelf-coolant",
    name: "TotalEnergies Glacelf Auto Supra Coolant",
    slug: "total-glacelf-coolant",
    category: { name: "Refrigerantes", slug: "coolant" },
    brand: { name: "TotalEnergies", slug: "totalenergies" },
    price: 55000,
    sku: "TOT-GLACELF-COOL",
    description: "Anticongelante y refrigerante de larga vida (OAT) para protección del radiador.",
    image: "/coolant.png",
    images: [{ url: "/coolant.png", alt: "Coolant TotalEnergies", isMain: true }],
    inStock: true,
    stock: 40,
  },

  // FRENOS Y SUSPENSIÓN
  {
    id: "motul-dot-4",
    name: "Motul DOT 4 Brake Fluid",
    slug: "motul-dot-4",
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: "Motul", slug: "motul" },
    price: 38000,
    sku: "MOT-DOT4-BRAKE",
    description: "Líquido de frenos sintético 100% poliglicol para sistemas hidráulicos y ABS.",
    image: "/frenos-liq.png",
    images: [{ url: "/frenos-liq.png", alt: "Líquido Frenos DOT 4", isMain: true }],
    inStock: true,
    stock: 50,
  },
  {
    id: "incolbest-pastillas-delanteras",
    name: "Pastillas de Freno Delanteras Incolbest",
    slug: "incolbest-pastillas-delanteras",
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: "Incolbest", slug: "incolbest" },
    price: 85000,
    sku: "INC-PAD-FRONT",
    description: "Pastillas de freno formulación cerámica de alto frenado y bajo desgaste de disco.",
    image: "/incolbest-pastillas-menu.png",
    images: [{ url: "/incolbest-pastillas-menu.png", alt: "Pastillas Incolbest", isMain: true }],
    inStock: true,
    stock: 35,
  },
  {
    id: "incolbest-discos-freno",
    name: "Discos de Freno Ventilados Incolbest",
    slug: "incolbest-discos-freno",
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: "Incolbest", slug: "incolbest" },
    price: 165000,
    sku: "INC-ROTOR-VENT",
    description: "Par de discos de freno ventilados con maquinado de alta precisión.",
    image: "/incolbest-discos-menu.png",
    images: [{ url: "/incolbest-discos-menu.png", alt: "Discos Incolbest", isMain: true }],
    inStock: true,
    stock: 18,
  },
  {
    id: "gabriel-amortiguador-gas",
    name: "Amortiguador Gabriel Gas-Matic Delantero",
    slug: "gabriel-amortiguador-gas",
    category: { name: "Frenos y Suspensión", slug: "frenos-y-suspension" },
    brand: { name: "Gabriel", slug: "gabriel" },
    price: 195000,
    sku: "GAB-GAS-FRONT",
    description: "Amortiguador presurizado con nitrógeno para máxima estabilidad y confort en ruta.",
    image: "/gabriel-amortiguador-01.png",
    images: [{ url: "/gabriel-amortiguador-01.png", alt: "Amortiguador Gabriel", isMain: true }],
    inStock: true,
    stock: 22,
  },

  // FILTROS
  {
    id: "wix-wl7570-filtro-aceite",
    name: "Filtro de Aceite WIX WL7570",
    slug: "wix-wl7570-filtro-aceite",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "WIX Filters", slug: "wix" },
    price: 32000,
    sku: "WIX-WL7570",
    description: "Filtro de aceite blindado para máxima retención de impurezas y flujo de lubricante.",
    image: "/01_wix_wl7570_filtro_aceite.png",
    images: [{ url: "/01_wix_wl7570_filtro_aceite.png", alt: "Filtro WIX WL7570", isMain: true }],
    inStock: true,
    stock: 75,
  },
  {
    id: "wix-wa9906-filtro-aire",
    name: "Filtro de Aire WIX WA9906 Panel",
    slug: "wix-wa9906-filtro-aire",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "WIX Filters", slug: "wix" },
    price: 45000,
    sku: "WIX-WA9906",
    description: "Filtro de aire tipo panel de alta eficiencia para admisión del motor.",
    image: "/02_wix_wa9906_filtro_aire.png",
    images: [{ url: "/02_wix_wa9906_filtro_aire.png", alt: "Filtro Aire WIX", isMain: true }],
    inStock: true,
    stock: 40,
  },
  {
    id: "auto-coexito-filtro-cabina",
    name: "Filtro de Cabina / Habitáculo Coéxito",
    slug: "auto-coexito-filtro-cabina",
    category: { name: "Filtros", slug: "filtros" },
    brand: { name: "Coéxito", slug: "coexito" },
    price: 38000,
    sku: "COX-COAC-305",
    description: "Filtro antipolen para aire acondicionado y purificación de aire en cabina.",
    image: "/07_auto_coexito_coac_305_filtro_cabina.png",
    images: [{ url: "/07_auto_coexito_coac_305_filtro_cabina.png", alt: "Filtro Cabina Coéxito", isMain: true }],
    inStock: true,
    stock: 30,
  },

  // GRASAS Y ADITIVOS
  {
    id: "mobil-grease-xhp-222",
    name: "Mobilgrease XHP 222 Complejo de Litio",
    slug: "mobil-grease-xhp-222",
    category: { name: "Grasas y Aditivos", slug: "grasas-y-aditivos" },
    brand: { name: "Mobil", slug: "mobil" },
    price: 35000,
    sku: "MOB-XHP222-GRS",
    description: "Grasa de complejo de litio para rodamientos, chasis y condiciones severas de carga.",
    image: "/caneca.png",
    images: [{ url: "/caneca.png", alt: "Mobilgrease XHP 222", isMain: true }],
    inStock: true,
    stock: 50,
  },

  // UREA AUTOMOTRIZ (DEF)
  {
    id: "urea-automotriz-def-5gal",
    name: "Urea Automotriz Grado Automotriz DEF / AdBlue",
    slug: "urea-automotriz-def-5gal",
    category: { name: "Urea Automotriz", slug: "urea" },
    brand: { name: "Coéxito", slug: "coexito" },
    price: 68000,
    sku: "DEF-UREA-5GAL",
    description: "Solución de urea al 32.5% de alta pureza para reducción catalítica selectiva SCR.",
    image: "/urea.png",
    images: [{ url: "/urea.png", alt: "Urea DEF Automotriz", isMain: true }],
    inStock: true,
    stock: 60,
  },

  // RADIADORES Y SISTEMA DE ENFRIAMIENTO
  {
    id: "radiador-aluminio-toyota-hilux-fortuner",
    name: "Radiador de Aluminio Toyota Hilux / Fortuner 2.5 - 3.0 Diésel (1KD/2KD)",
    slug: "radiador-aluminio-toyota-hilux-fortuner",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Toyota", slug: "toyota" },
    price: 420000,
    sku: "RAD-TOY-HLX-1KD",
    description: "Radiador de alta disipación térmica con panel de aluminio soldado y tanques reforzados. Compatible con Toyota Hilux y Fortuner motor 1KD/2KD diésel.",
    image: "/radiador-auto.jpg",
    images: [{ url: "/radiador-auto.jpg", alt: "Radiador Toyota Hilux Fortuner", isMain: true }],
    inStock: true,
    stock: 15,
  },
  {
    id: "radiador-chevrolet-sail-14",
    name: "Radiador Chevrolet Sail 1.4L con/sin Aire Acondicionado",
    slug: "radiador-chevrolet-sail-14",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Chevrolet", slug: "chevrolet" },
    price: 240000,
    sku: "RAD-CHV-SAIL-14",
    description: "Radiador completo de aluminio con tanques de polímero térmico para Chevrolet Sail 1.4 todos los modelos.",
    image: "/radiador-banner.jpg",
    images: [{ url: "/radiador-banner.jpg", alt: "Radiador Chevrolet Sail 1.4", isMain: true }],
    inStock: true,
    stock: 20,
  },
  {
    id: "radiador-renault-duster-logan-sandero",
    name: "Radiador Renault Duster / Logan / Sandero / Stepway 1.6 - 2.0 16V",
    slug: "radiador-renault-duster-logan-sandero",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Renault", slug: "renault" },
    price: 280000,
    sku: "RAD-REN-DUST-K4M",
    description: "Radiador para sistema de refrigeración de motores Renault K4M / F4R. Enfriamiento óptimo para clima cálido.",
    image: "/radiador-auto.jpg",
    images: [{ url: "/radiador-auto.jpg", alt: "Radiador Renault Duster Sandero", isMain: true }],
    inStock: true,
    stock: 18,
  },
  {
    id: "radiador-isuzu-npr-camion-pesado",
    name: "Radiador Reforzado Camión Isuzu NPR / NQR / Chevrolet NPR Turbo",
    slug: "radiador-isuzu-npr-camion-pesado",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Isuzu", slug: "isuzu" },
    price: 850000,
    sku: "RAD-ISZ-NPR-HD",
    description: "Radiador de servicio pesado para camiones diésel con panel multicelda de alta capacidad de transferencia térmica para transporte y carga pesada.",
    image: "/radiador-pesado.jpg",
    images: [{ url: "/radiador-pesado.jpg", alt: "Radiador Isuzu NPR Camión", isMain: true }],
    inStock: true,
    stock: 8,
  },
  {
    id: "tapa-radiador-presurizada-11-bar",
    name: "Tapa de Radiador Presurizada de Seguridad 1.1 Bar (16 PSI)",
    slug: "tapa-radiador-presurizada-11-bar",
    category: { name: "Radiadores", slug: "radiadores" },
    brand: { name: "Bosch", slug: "bosch" },
    price: 32000,
    sku: "CAP-RAD-11-BAR",
    description: "Tapa presurizada de acero inoxidable con sello de caucho sintético de alta temperatura y válvula de escape para control óptimo de presión del circuito de refrigeración.",
    image: "/coolant.png",
    images: [{ url: "/coolant.png", alt: "Tapa Radiador 1.1 Bar", isMain: true }],
    inStock: true,
    stock: 50,
  },
];

export function getProductById(id) {
  return products.find(p => p.id === id || p.slug === id);
}
